format_version: 10
pipelines:
  gocd.build:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-8e24be0:
        git: git@github.com:belskiiartem/gocdbuildtest.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          maven:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - mvn
                - install
                command: 'CMD:'
                run_if: passed
